name: Build with SPM

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.x
      - name: Enable SPM
        run: |
          flutter config --enable-swift-package-manager
      - name: Doctor
        # Run doctor, for ease of debugging any issues.
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter packages get
        working-directory: example
      - name: Cleans up iOS project
        run: |
          pod deintegrate
          echo "#include \"Generated.xcconfig\"" > Flutter/Debug.xcconfig
          cat Flutter/Debug.xcconfig
          echo "#include \"Generated.xcconfig\"" > Flutter/Release.xcconfig
          cat Flutter/Release.xcconfig
        working-directory: example/ios
      - name: Build iOS
        run: flutter build ios --debug --no-codesign --simulator
        working-directory: example
